package de.open4me.hibiscus.reports.automation.sql;

public final class AutomationSqlDialectTests
{
    private AutomationSqlDialectTests()
    {
    }

    public static void run()
    {
        detectsMysqlCompatibleDialects();
        keepsDefaultIdentityDialect();
        createsTransactionTriggerEventMigration();
    }

    private static void detectsMysqlCompatibleDialects()
    {
        check(AutomationSqlDialect.forProductName("MySQL").idColumn().contains("auto_increment"),
            "mysql id column");
        check(AutomationSqlDialect.forProductName("MariaDB").idColumn().contains("auto_increment"),
            "mariadb id column");
    }

    private static void keepsDefaultIdentityDialect()
    {
        check(AutomationSqlDialect.forProductName("H2").idColumn().contains("generated by default as identity"),
            "h2 id column");
        check(AutomationSqlDialect.forProductName(null).idColumn().contains("generated by default as identity"),
            "unknown id column");
    }

    private static void createsTransactionTriggerEventMigration()
    {
        java.util.List<AutomationSqlChange> changes = AutomationSqlChange.changesSince(2,
            AutomationSqlDialect.forProductName("H2"));

        check(changes.size() == 2, "two migrations after version 2");
        check(changes.get(0).version() == 3, "transaction event migration version");
        check(changes.get(1).version() == 4, "transaction event status migration version");
        String sql = String.join("\n", changes.get(0).statements()) + "\n"
            + String.join("\n", changes.get(1).statements());
        check(sql.contains("automation_trigger_event"), "migration creates event table");
        check(sql.contains("trigger_id, event_type, event_key"), "migration creates unique event key");
        check(sql.contains("event_status"), "migration adds event status");
    }

    private static void check(boolean condition, String message)
    {
        if (!condition)
            throw new AssertionError(message);
    }
}
