package de.open4me.hibiscus.reports.automation.sql;

public final class AutomationSqlDialectTests
{
    private AutomationSqlDialectTests()
    {
    }

    public static void run()
    {
        detectsMysqlCompatibleDialects();
        keepsDefaultIdentityDialect();
    }

    private static void detectsMysqlCompatibleDialects()
    {
        check(AutomationSqlDialect.forProductName("MySQL").idColumn().contains("auto_increment"),
            "mysql id column");
        check(AutomationSqlDialect.forProductName("MariaDB").idColumn().contains("auto_increment"),
            "mariadb id column");
    }

    private static void keepsDefaultIdentityDialect()
    {
        check(AutomationSqlDialect.forProductName("H2").idColumn().contains("generated by default as identity"),
            "h2 id column");
        check(AutomationSqlDialect.forProductName(null).idColumn().contains("generated by default as identity"),
            "unknown id column");
    }

    private static void check(boolean condition, String message)
    {
        if (!condition)
            throw new AssertionError(message);
    }
}
