package de.open4me.hibiscus.reports.automation.sql;

public final class AutomationSqlDialectTests
{
    private AutomationSqlDialectTests()
    {
    }

    public static void run()
    {
        detectsMysqlCompatibleDialects();
        keepsDefaultIdentityDialect();
        createsTransactionTriggerEventMigration();
    }

    private static void detectsMysqlCompatibleDialects()
    {
        check(AutomationSqlDialect.forProductName("MySQL").idColumn().contains("auto_increment"),
            "mysql id column");
        check(AutomationSqlDialect.forProductName("MariaDB").idColumn().contains("auto_increment"),
            "mariadb id column");
    }

    private static void keepsDefaultIdentityDialect()
    {
        check(AutomationSqlDialect.forProductName("H2").idColumn().contains("generated by default as identity"),
            "h2 id column");
        check(AutomationSqlDialect.forProductName(null).idColumn().contains("generated by default as identity"),
            "unknown id column");
    }

    private static void createsTransactionTriggerEventMigration()
    {
        java.util.List<AutomationSqlChange> changes = AutomationSqlChange.changesSince(2,
            AutomationSqlDialect.forProductName("H2"));

        check(changes.size() == 1, "one migration after version 2");
        AutomationSqlChange change = changes.get(0);
        check(change.version() == 3, "transaction event migration version");
        String sql = String.join("\n", change.statements());
        check(sql.contains("automation_trigger_event"), "migration creates event table");
        check(sql.contains("trigger_id, event_type, event_key"), "migration creates unique event key");
    }

    private static void check(boolean condition, String message)
    {
        if (!condition)
            throw new AssertionError(message);
    }
}
