package de.open4me.hibiscus.reports.automation.sql;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.Locale;

public final class AutomationSqlDialect
{
    private final boolean mysql;

    private AutomationSqlDialect(boolean mysql)
    {
        this.mysql = mysql;
    }

    public static AutomationSqlDialect detect(Connection connection) throws SQLException
    {
        String name = connection.getMetaData().getDatabaseProductName();
        return forProductName(name);
    }

    static AutomationSqlDialect forProductName(String name)
    {
        String normalized = name == null ? "" : name.toLowerCase(Locale.ROOT);
        return new AutomationSqlDialect(normalized.contains("mysql") || normalized.contains("mariadb"));
    }

    public String idColumn()
    {
        return mysql ? "int NOT NULL auto_increment" : "integer generated by default as identity";
    }

    public String text()
    {
        return mysql ? "longtext" : "clob";
    }

    public String bool()
    {
        return mysql ? "tinyint(1)" : "boolean";
    }

    public String timestamp()
    {
        return "timestamp";
    }

    public String now()
    {
        return "CURRENT_TIMESTAMP";
    }

    public String trueValue()
    {
        return mysql ? "1" : "true";
    }

    public String falseValue()
    {
        return mysql ? "0" : "false";
    }
}
